version: "3"

backend:
  db:
    image: mysql:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - node_mysql_network
  server:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:5000"
    volumes:
      - ".:/usr/app/src"
    networks:
      - node_mysql_network

networks:
  node_mysql_network:
    driver: bridge