version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSOWRD}'
    ports:
      - "3306:3306"
    networks:
      - node_mysql_network
  server:
    build: .
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    ports:
      - "80:5000"
    volumes:
      - ".:/usr/app/src"
    networks:
      - node_mysql_network

networks:
  node_mysql_network:
    driver: bridge
